#!/usr/bin/env bash

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

set -euo pipefail

APP_HOME=$(cd "${0%/*}" && pwd -P)

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
  echo "Gradle wrapper jar not found. Please run 'gradle wrapper' locally." >&2
  exit 1
fi

exec java ${JAVA_OPTS:-} -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
